spring:
  profiles:
    active: test
---


spring:
  profiles: test
  application:
    name: configclient-test

server:
  port: 8801

busi:
  ops: N
secret:
  password: '{cipher}6adefbbfcefd6f424ff01bf4fe94288556acf1fdabb658417c964b0cab694423'
---
spring:
  profiles: prod
  application:
    name: configclient-test

server:
  port: 8811

busi:
  ops: Y
secret:
  password: '{cipher}6adefbbfcefd6f424ff01bf4fe94288556acf1fdabb658417c964b0cab694423'
