spring:
  profiles:
    active: test
---


spring:
  profiles: test
  application:
    name: configclient-test

server:
  port: 8801

busi:
  ops: N
---
spring:
  profiles: prod
  application:
    name: configclient-test

server:
  port: 8811

busi:
  ops: Y
